config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :users
  root 'pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'teachers', to: 'users#teachers', as: 'teachers_list'
  get 'students', to: 'users#students', as: 'students_list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :require_administrative

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
      <%= form_with(model: role) do |form| %>
        <% if role.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

            <ul>
              <% role.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group row">
          <%= form.label :name,class:"col-2 col-form-label"%>
          <div class="col-5">
            <%= form.text_field :name,rows:4,class:"form-control shadow rounded",placeholder:"Enter Role Name",required: true %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :description,class:"col-2 col-form-label"%>
          <div class="col-5">
            <%= form.text_area :description,rows:4,class:"form-control shadow rounded",placeholder:"Enter description" %>
          </div>
        </div>
        <div class="row">
          <div class="actions form-group offset-md-2 col-md-2 text-center">
            <%= form.submit class:"btn btn-success btn-lg"  %>
          </div>
          <div class="form-group  col-md-4  text-center">
            <%= link_to 'Cancel', :back,class:"btn btn-danger btn-lg" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/roles/edit.html.erb
<div class="w-100 row align-items-center breadcrumbb ml-0 mb-5">
    <div class="offset-md-4 col-md-4 text-center">
          <h1 class="text-center mt-4"> Edit Role </h1>
    </div>
    <div class="col-md-4 text-right"> 
        <span>
		    <span class="breadcrumb-item"><%= link_to "Role's", roles_path %></span>
		    <span class="breadcrumb-item active" aria-current="page">Edit Role</span>
        <span>
    </div>
 </div>

<%= render 'form', role: @role %>

app/views/roles/index.html.erb
<div class="w-100 row align-items-center breadcrumbb ml-0 mb-5">
    <div class="offset-md-4 col-md-4 text-center">
          <h1 class="text-center mt-4">Role Details </h1>
    </div>
    <div class="col-md-4 text-right"> 
        <span>
            <span class="breadcrumb-item"><%= link_to 'Home', root_path %></span>
		    <span class="breadcrumb-item"><%= link_to 'Create Role', new_role_path %></span>
            <span class="breadcrumb-item active" aria-current="page">Role Details</span>
        <span>
    </div>
</div>


<div class="container" style="overflow-x: auto;">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Sl. no.</th>
				<th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col"class=" text-center" colspan="2">Action</th>
                
			</tr>
		</thead>
		<%@count=0%>
		<% @roles.each do |role| %>
            <tbody>
                <%@count=@count+1%>
                <tr>
                    <th scope="row"><%= @count%></th>
                    <td><%= role.name %></td>
                    <td><%= role.description %></td>
                    <td><%= link_to 'Edit', edit_role_path(role), class:"btn btn-outline-primary" %></td>
                    <td><%= link_to 'Delete', role, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger" %></td>
                        
                </tr>
                            
            </tbody>
		<%end%>
	</table>
				
</div>

app/views/roles/new.html.erb
<div class="w-100 row align-items-center breadcrumbb ml-0 mb-5">
    <div class="offset-md-4 col-md-4 text-center">
          <h3 class="text-center mt-4"> New Role </h3>
    </div>
    <div class="col-md-4 text-right"> 
        <span>
		    <span class="breadcrumb-item"><%= link_to "Roles", roles_path %></span>
		    <span class="breadcrumb-item active" aria-current="page">New  Role </span>
        <span>
    </div>
 </div>

<%= render 'form', role: @role %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>