config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :users
  root 'pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'teachers', to: 'users#teachers', as: 'teachers_list'
  get 'students', to: 'users#students', as: 'students_list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
<div class="container text-center">
  <small>Copyright &copy; Your Website</small>
</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name,msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg%>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag "logoschoolmanagement.jpg", height: 40, width:40 %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%=link_to 'Home', root_path,class:"nav-link" %>
      </li>
      <% if logged_in? %>
        <% if current_user.role.name != 'student' %>
           <%=link_to 'Student', students_list_path,class:"nav-link" %>
        <% end %>
        <% if current_user.role.name=='principal' %>
          <li class="nav-item active">
            <%=link_to 'Teacher', teachers_list_path,class:"nav-link" %>
          </li>
          <li class="nav-item active">
            <%=link_to 'Users', users_path,class:"nav-link" %>
          </li>
          <li class="nav-item active">
            <%=link_to 'Roles', roles_path,class:"nav-link" %>
          </li>
        <% end %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <% if current_user.role.name == 'principal' %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
            <% end %>
          </div>
        </li>
        <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
          </li>
      
      <% else %>
        <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newschoolmanagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
  <%=render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
        
        <%= yield %>
        
      </div>
     <%=render 'layouts/footer' %>
  </body>
</html>